### ISSUE TITLE
Module resolution fails in symlinked preset/mixin package 📦, and does not abide to "--preserve-symlinks" node option

### ISSUE THREAD

**Issue by hossam-magdy** [xing/hops#1257]
## This is my intent (choose one)

- [x] I want to report a bug
- [x] I want to request a feature or change
- [x] I want to provide or change a feature

## The problem

While developing a mixin-and-preset package to be loaded inside any hops application, using `yarn link`, `npm link` or "yarn workspaces", the package is not hooked gracefully during the bootstrap phase of hops.

In other words, resolving peerDependencies of a **symlinked** hops mixin-and-preset package fails, even when using the [`--preserve-symlinks` node arg](https://nodejs.org/api/all.html#cli_preserve_symlinks) which as describe in the official node documentation as a way to interpret node resolution algorithm to treat symlinks as preserved (as if they are normal dirs). A further detailed article can be found [here](https://chevtek.io/you-can-finally-npm-link-packages-that-contain-peer-dependencies/).

### Steps done to reproduce:

Although it was not that straight-forward to get it concrete, but I think the steps to reproduce the issue, can be narrowed down to the following:

1. Have/Create any working/runnable hops application. Assuming in path `~/hops-app`.
2. Create a new separate directory, assuming in path `~/my-hops-preset`, with:

   ```js
   // file: ~/my-hops-preset/package.json
   // including a `preset` field, as stated in docs: https://github.com/xing/hops/blob/v12.x/DOCUMENTATION.md#presets-1
   {
     "name": "my-hops-preset",
     "preset": "path-to/preset.js",
     "peerDependencies": {
       "hops": "*",  // or "hops-mixin"
     },
   }
   ```

   ```js
   // file: ~/my-hops-preset/path-to/preset.js
   module.exports = { mixins: [__dirname] };
   ```

   ```js
   // file: ~/my-hops-preset/path-to/mixin.core.js
   // As described in docs: https://github.com/xing/hops/blob/v12.x/DOCUMENTATION.md#creating-your-first-core-mixin
   const { Mixin } = require('hops');

   class MyMixin extends Mixin {
     configureBuild(webpackConfig) {
       webpackConfig.resolve.alias['my-modules'] = path.resolve(
         this.config.rootDir,
         'my-aliased-modules'
       );
     }
   }

   module.exports = MyMixin;
   ```

3. Add `my-hops-preset` as a dependency (or devDep) in the `hops-app`

   ```js
   // file: ~/hops-app/package.json
   {
     "dependencies": {
       "my-hops-preset": "*"
     }
   }
   ```

4. - In `~/my-hops-preset`, run `yarn link`
   - In `~/hops-app`, run:
     - `yarn link my-hops-preset`
     - `yarn install`

5. Start the "hops-app", with [`--preserve-symlinks` node arg](https://nodejs.org/api/all.html#cli_preserve_symlinks). In `~/hops-app`, run:
   - `NODE_PRESERVE_SYMLINKS=1 yarn hops start`
   - or `NODE_OPTIONS='--preserve-symlinks' yarn hops start`
   - or `node --preserve-symlinks ./node_modules/.bin/hops start`

6. Error:

   ```
   Error: Cannot find module 'hops'
   Require stack:
   - /Users/USERNAME/my-hops-preset/path-to/mixin.core.js
   - /Users/USERNAME/hops-app/node_modules/hops-bootstrap/lib/config.js
   - /Users/USERNAME/hops-app/node_modules/hops-bootstrap/index.js
   - /Users/USERNAME/hops-app/node_modules/hops-yargs/index.js
   - /Users/USERNAME/hops-app/node_modules/hops/bin.js
   - /Users/USERNAME/hops-app/node_modules/@xingternal/hops/bin/hops.js
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
       at Function.Module._load (internal/modules/cjs/loader.js:840:27)
       at Module.require (internal/modules/cjs/loader.js:1019:19)
       at require (internal/modules/cjs/helpers.js:77:18)
       at Object.<anonymous> (/Users/USERNAME/my-hops-preset/path-to/mixin.core.js:2:22)
       at Module._compile (internal/modules/cjs/loader.js:1133:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
       at Module.load (internal/modules/cjs/loader.js:977:32)
       at Function.Module._load (internal/modules/cjs/loader.js:877:14)
       at Module.require (internal/modules/cjs/loader.js:1019:19)
   error Command failed with exit code 1.
   ```

## Analysis

After an arduous journey to analyse the rootcause of the problem, it is elaborated to me that during hops bootstrap stage, it uses [`enhanced-resolve`](https://github.com/webpack/enhanced-resolve) to resolve the presets and mixins from the installed packages.

And after further investigation of this package: the custom resolvers created via this package doesn't abide to the node arguments that impact the module resolution in node. But instead the custom resolvers are completely configurable. Specifically, setting `NODE_PRESERVE_SYMLINK=1` has no effect on the enhanced resolvers because the take `symlinks` boolean option [default=true](), and [it was assured](https://github.com/webpack/enhanced-resolve/blob/235c947e/lib/ResolverFactory.js#L170) that this boolean option is not impacted by the `NODE_PRESERVE_SYMLINK` env var.

_NOTE_: based on node documentation, all three ways below should **preserve the symlinks path in module resolution of node**, yet it was tested that all of them have no effect:

- `NODE_PRESERVE_SYMLINK=1 node ./entryFile.js`
- `NODE_OPTIONS='--preserve-symlinks' node ./entryFile.js`
- `node --preserve-symlinks ./entryFile.js`

**UPDATE**: After even further investigation, it turned out that the main/only effective part causing the resolution to fail, is the particular preset resolution, happening [here](https://github.com/xing/hops/blob/34ef9afeab857144165a9fe30c5d35dbb56c450f/packages/bootstrap/lib/loader.js#L18), so if this `presetJsFilePath` is the unpreservedSymlink/real path, not the symlink one, the mixin paths of this preset will be also the real paths. Which leads to any further package resolution within those mixins to be relative to the real path instead of the preservedSymlink one.

## Proposed solution

In [the resolver of bootstrap package](https://github.com/xing/hops/blob/e7a3b46/packages/bootstrap/lib/resolver.js), during any usage of [`createResolver`](https://github.com/webpack/enhanced-resolve#creating-a-resolver) we need to pass `symlinks` option as `false` if the pre-mentioned env vars are set and have the pre-mentioned values. I.e:

```js
const defaultConfig = {
  symlinks: !(
    process.env.NODE_PRESERVE_SYMLINKS == 1 ||
    (typeof process.env.NODE_OPTIONS === 'string' &&
      process.env.NODE_OPTIONS.includes('--preserve-symlinks')) ||
    process.execArgv.includes('--preserve-symlinks')
  ),
};

// …
createResolver({
  ...defaultConfig,
  // the other config
});
```

It was proven that loading the hops-preset and hops-mixins work correctly and as expected by adding `symlinks: false` option to the createResolver, specifically in [resolvePreset](https://github.com/xing/hops/blob/e7a3b46/packages/bootstrap/lib/resolver.js#L12) and [resolveMixins](https://github.com/xing/hops/blob/e7a3b46/packages/bootstrap/lib/resolver.js#L17).

<del>**Caveat of the solution:**</del>

<del>The solution works perfectly for both: `NODE_PRESERVE_SYMLINK=1 node ./entryFile.js` and `NODE_OPTIONS='--preserve-symlinks' node ./entryFile.js` But not for `node --preserve-symlinks ./entryFile.js`. And I am not aware of a way to read the arguments passed to the node exectuable.</del>

**UPDATE**: After talking to @ZauberNerd , and he thankfully introduced me to `process.execArgv`, I updated the example above. There is even a thought to set `symlinks` field to be always `false` which would also fix this specific issue for all 3 different ways of launching node in "preserve-symlinks" mode.

**Comment by hossam-magdy** [comment]
Resolved by #1258
