### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by drixsonic** [xing/hops#137]
Is Hops supposed to work with code splitting? I'm getting this error when trying:

```
 94% asset optimization[HOPS PLUGIN ERROR]: { Error: Cannot find module './chunk-0.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.requireEnsure [as e] (/Users/drix/dev/projects/playground/hops-code-splitting/dist/bundle.js:41:25)
    at Object.getIndexRoute (/Users/drix/dev/projects/playground/hops-code-splitting/dist/bundle.js:180:25)
    at getIndexRoute (/Users/drix/dev/projects/playground/hops-code-splitting/node_modules/react-router/lib/matchRoutes.js:68:35)
    at /Users/drix/dev/projects/playground/hops-code-splitting/node_modules/react-router/lib/matchRoutes.js:153:9
    at matchRouteDeep (/Users/drix/dev/projects/playground/hops-code-splitting/node_modules/react-router/lib/matchRoutes.js:176:8)
    at /Users/drix/dev/projects/playground/hops-code-splitting/node_modules/react-router/lib/matchRoutes.js:244:5 code: 'MODULE_NOT_FOUND' }
Hash: 4a0f11896f9ba5447933
```

I'm maybe doing things wrong with Webpack2... Here is a repo you can clone to reproduce the issue: https://github.com/drixsonic/hops-code-splitting

**Comment by dmbch** [comment]
Hi @drixsonic, thanks for asking. I guess we'll have to add [another plugin](https://webpack.github.io/docs/list-of-plugins.html#limitchunkcountplugin) to the web pack config used for server side rendering for code splitting to work:

```
new webpack.optimize.LimitChunkCountPlugin({
  maxChunks: 1
})
```

I've done just that for the next major hops version in 13b5c923fa55ba07608e2ed5a7afd10a770411f3

**Comment by drixsonic** [comment]
Great, I'll give it a try with the new version :)
